### ISSUE TITLE
value too long for type character varying(500) - BOM Upload

### ISSUE THREAD

**Issue by r00sta** [inventree/inventree-docs#228]
Running into this error when uploading a BOM.

Anyone seen this before? Wanted to ask before I start messing around with the DB directly...

**Full Error Log**

Traceback (most recent call last):

File "/home/inventree/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
return self.cursor.execute(sql, params)

psycopg2.errors.StringDataRightTruncation: value too long for type character varying(500)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

File "/home/inventree/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/inventree/.local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
return self.dispatch(request, *args, **kwargs)

File "/home/inventree/.local/lib/python3.8/site-packages/django/contrib/auth/mixins.py", line 104, in dispatch
return super().dispatch(request, *args, **kwargs)

File "/home/inventree/.local/lib/python3.8/site-packages/formtools/wizard/views.py", line 244, in dispatch
response = super().dispatch(request, *args, **kwargs)

File "/home/inventree/.local/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
return handler(request, *args, **kwargs)

File "/home/inventree/InvenTree/common/views.py", line 460, in post
return super().post(*args, **kwargs)

File "/home/inventree/.local/lib/python3.8/site-packages/formtools/wizard/views.py", line 302, in post
return self.render_done(form, **kwargs)

File "/home/inventree/.local/lib/python3.8/site-packages/formtools/wizard/views.py", line 358, in render_done
done_response = self.done(list(final_forms.values()), form_dict=final_forms, **kwargs)

File "/home/inventree/InvenTree/part/views.py", line 955, in done
item.save()

File "/home/inventree/InvenTree/part/models.py", line 2608, in save
super().save(*args, **kwargs)

File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/base.py", line 739, in save
self.save_base(using=using, force_insert=force_insert,

File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/base.py", line 776, in save_base
updated = self._save_table(

File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/base.py", line 881, in _save_table
results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)

File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/base.py", line 919, in _do_insert
return manager._insert(

File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs)

File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/query.py", line 1270, in _insert
return query.get_compiler(using=using).execute_sql(returning_fields)

File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
cursor.execute(sql, params)

File "/home/inventree/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)

File "/home/inventree/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
return executor(sql, params, many, context)

File "/home/inventree/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
return self.cursor.execute(sql, params)

File "/home/inventree/.local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
raise dj_exc_value.with_traceback(traceback) from exc_value

File "/home/inventree/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
return self.cursor.execute(sql, params)

django.db.utils.DataError: value too long for type character varying(500)

**Comment by matmair** [comment]
@r00sta hi there!
This repo is only for documentation issues. Please use the inventree/inventree repo and fill out the bug report issue template.
Thanks

**Comment by SchrodingersGat** [comment]
https://github.com/inventree/InvenTree/issues
