### ISSUE TITLE
invoke superuser hangs

### ISSUE THREAD

**Issue by nelsonov** [inventree/inventree-docs#263]
Doing a bare metal install on Raspberry Pi 4B / Raspberry Pi OS 10.  

```
(env) inventree@rpi07:~/src $ invoke superuser
Username (leave blank to use 'inventree'): inventree

```
At this point it just hangs.  There's a CR/LF after the Username prompt, but nothing further happens.  I can launch the gunicorn server and see the login page, but, of course, there's no password with which to log in.

**Comment by nelsonov** [comment]
Forgot to mention, using MariaDB as the database.  I can log in to the database from the command line using the same credentials that are in the config.yaml.

**Comment by nelsonov** [comment]
Here's the trace after I hit ctl-c:
^CTraceback (most recent call last):                                                                                                                                                          
  File "/usr/bin/invoke", line 9, in <module>                                                                                                                                                 
    load_entry_point('invoke==0.11.1', 'console_scripts', 'invoke')()                                                                                                                         
  File "/usr/lib/python3/dist-packages/invoke/cli.py", line 438, in main
    dispatch(sys.argv)
  File "/usr/lib/python3/dist-packages/invoke/cli.py", line 431, in dispatch
    return executor.execute(*tasks)
  File "/usr/lib/python3/dist-packages/invoke/executor.py", line 100, in execute
    task=task, name=name, args=args, kwargs=kwargs, config=config
  File "/usr/lib/python3/dist-packages/invoke/executor.py", line 153, in _execute
    result = task(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/invoke/tasks.py", line 111, in __call__
    result = self.body(*args, **kwargs)
  File "/home/inventree/src/tasks.py", line 115, in superuser
    manage(c, 'createsuperuser', pty=True)
  File "/home/inventree/src/tasks.py", line 72, in manage
    ), pty=pty)
  File "/usr/lib/python3/dist-packages/invoke/context.py", line 53, in run
    return runner_class(context=self).run(command, **kwargs)
  File "/usr/lib/python3/dist-packages/invoke/runners.py", line 252, in run
    self.wait()
  File "/usr/lib/python3/dist-packages/invoke/runners.py", line 486, in wait
    pid_val, self.status = os.waitpid(self.pid, 0)
KeyboardInterrupt

**Comment by SchrodingersGat** [comment]
In addition to having the mariadb server running, have you created an 'inventree' database?

**Comment by SchrodingersGat** [comment]
Also, please re-open this issue over at the main inventree code repo - https://github.com/inventree/InvenTree/issues
