### ISSUE TITLE
Error During Installation

### ISSUE THREAD

**Issue by guillaumesoucy94** [inventree/inventree-docs#344]
Hello, 

I'm trying to deploy Inventree. I'd followed all steps from here: https://inventree.readthedocs.io/en/latest/start/install/ and it give me that error when doing: invoke update

```
Traceback (most recent call last):
  File "/mnt/disk/inventree/src/InvenTree/manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/mnt/disk/inventree/env/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/mnt/disk/inventree/env/lib/python3.10/site-packages/django/core/management/__init__.py", line 363, in execute
    settings.INSTALLED_APPS
  File "/mnt/disk/inventree/env/lib/python3.10/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/mnt/disk/inventree/env/lib/python3.10/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/mnt/disk/inventree/env/lib/python3.10/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/disk/inventree/src/InvenTree/InvenTree/settings.py", line 86, in <module>
    STATIC_ROOT = config.get_static_dir()
  File "/mnt/disk/inventree/src/InvenTree/InvenTree/config.py", line 133, in get_static_dir
    raise FileNotFoundError('INVENTREE_STATIC_ROOT not specified')
FileNotFoundError: INVENTREE_STATIC_ROOT not specified
```

What I need to do to make it work?

Thank-you,

Guillaume

**Comment by SchrodingersGat** [comment]
Please see the docs here - https://inventree.readthedocs.io/en/latest/start/config/#static-file-storage - you need to provide a location for the server to place static files

Also see https://inventree.readthedocs.io/en/latest/start/config/#uploaded-file-storage for `INVENTREE_MEDIA_ROOT`

**Comment by guillaumesoucy94** [comment]
Hello, 

I just provide the location for static files and the media root in /mnt/disk/inventree/src/InvenTree/config.yaml and when sending `invoke server` it return this:

`(env) root@inventory-dc:/mnt/disk/inventree/src# invoke server
Traceback (most recent call last):
  File "/mnt/disk/inventree/src/InvenTree/manage.py", line 9, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/disk/inventree/src/InvenTree/manage.py", line 15, in <module>
    import django  # noqa: F401
ModuleNotFoundError: No module named 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/disk/inventree/src/InvenTree/manage.py", line 17, in <module>
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?`

Did you forget to activate a virtual environment? It sent `python3 -m venv env
source ./env/bin/activate` and `(env)` is the prompt prefix.

Is I forget something?

Best regards, 

Guillaume

**Comment by matmair** [comment]
@guillaumesoucy94 please check if you installed into this directory / env with `inv update`. From the error message it does not seem like that.
